source "http://rubygems.org"

gem 'rubydoctest', :git => 'git://github.com/tslocke/rubydoctest.git'
gem 'rails'
gem 'responders', '~> 2.4'
gem 'protected_attributes_continued'
gemspec :path => "../dryml"
gemspec :path => "../hobo_support"
gemspec :path => "../hobo_fields"
gemspec
gem 'hobo_will_paginate'
platform :ruby do
  gem 'sqlite3'
end
platform :jruby do
  gem 'activerecord-jdbcsqlite3-adapter'
end

gem "irt"
