source "http://rubygems.org"

gem 'rubydoctest', :git => 'git://github.com/tslocke/rubydoctest.git'
gem 'rails'
gem 'bootsnap'
gem 'listen'
gem 'yard'
gem 'protected_attributes_continued', :github => 'sputnik8/protected_attributes_continued'
 
gem 'responders', '~> 2.4'

gemspec :path => "../hobo_support"
gemspec
platform :ruby do
  gem 'sqlite3'
end
platform :jruby do
  gem 'activerecord-jdbcsqlite3-adapter'
end
